---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
   - name: instance
#  - name: ubuntu
#    image: ubuntu:latest
provisioner:
  name: ansible
#  inventory:
#    host_vars:
      # setting for the platform instance named 'instance'
#      ubuntu:
#        ansible_user: ansible
verifier:
  name: ansible
            
