---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
  - image: centos:8
provisioner:
  name: ansible
  inventory:
    host_vars:
      # setting for the platform instance named 'instance'
      centos8:
        ansible_user: ansible
verifier:
  name: ansible
